import { StoryArticle } from "./StoryArticle";
import { StoryDomain } from "./StoryDomain";
import { StoryPerspectives } from "./StoryPerspectives";
import { StoryQna } from "./StoryQna";
import { StoryTimeline } from "./StoryTimeline";

export type Story = {
  id: string;
  cluster_number: number;
  unique_domains: number;
  number_of_titles: number;
  sourceLanguage: string;
  category: string;
  title: string;
  short_summary: string;
  did_you_know?: string;
  talking_points?: string[];
  quote?: string;
  quote_author?: string;
  quote_attribution?: string;
  quote_source_url?: string;
  quote_source_domain?: string;
  location?: string;
  perspectives?: StoryPerspectives[];
  emoji: string;
  historical_background: string;
  timeline: StoryTimeline[];
  technical_details?: string[];
  business_angle_text?: string;
  industry_impact: string[];
  suggested_qna: StoryQna[];
  articles: StoryArticle[];
  domains: StoryDomain[];
  humanitarian_impact?: string;
  travel_advisory?: string[];
  geopolictical_context?: string;
  international_reactions?: string[];
  economic_implications?: string;
  future_outlook?: string;
  business_angle_points?: string[];
  user_action_items?: string[];
  scientific_significance?: string[];
  destination_highlights?: string;
  culinary_significance?: string;
  performance_statistics?: string[];
  league_standings?: string;
  diy_tips?: string;
  design_principles?: string;
  user_experience_impact?: string[];
  gameplay_mechanics?: string[];
};
