export default [
  {
    type: "heading",
    defaultValue: "Settings",
  },
  {
    type: "section",
    items: [
      {
        type: "checkboxgroup",
        messageKey: "UserCategories",
        label: "Categories",
        description:
          "NOTE: Some categories may have limited content available. If there are no summaries for the day they will not show up in the app. Categories are manually kept up to date based on Kagi feeds. Selecting a large number of categories  (30+) may cause unexpected behavior.",
        defaultValue: [
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
        ],
        options: [
          "3D Printing",
          "Africa",
          "AI",
          "Apple",
          "Argentina",
          "Australia",
          "Austria",
          "Bay",
          "Belgium",
          "Bitcoin",
          "Brazil",
          "Business",
          "Canada",
          "Catholic",
          "China",
          "Coffee",
          "Colombia",
          "Costa Rica",
          "Croatia",
          "Cryptocurrency",
          "Cybersecurity",
          "Czech Republic",
          "Denmark",
          "Economy",
          "Estonia",
          "Europe",
          "Finland",
          "Formula 1",
          "France",
          "French Music",
          "Gaming",
          "Germany | Hesse",
          "Germany",
          "Google",
          "Greece",
          "Healthcare | USA",
          "Hong Kong",
          "Hungary",
          "India | Tamil Nadu",
          "India",
          "iRacing & Sim Racing",
          "Iran",
          "Ireland",
          "Israel",
          "Italy",
          "Japan",
          "Linux & OSS",
          "Lithuania",
          "Mexico",
          "Microsoft",
          "New Zealand",
          "NFL",
          "NHL",
          "Nintendo",
          "Norway",
          "Pakistan",
          "Palestine",
          "Philippines",
          "Podcasting",
          "Poland",
          "Portugal",
          "Privacy",
          "Romania",
          "Russia",
          "Science",
          "Serbia",
          "Simulation Games",
          "Singapore",
          "Slovakia",
          "Slovenia",
          "South Korea",
          "Spain",
          "Sports",
          "Sweden",
          "Switzerland (DE)",
          "Switzerland (FR)",
          "Taiwan",
          "Technology",
          "Thailand",
          "The Netherlands",
          "Turkey",
          "UK",
          "Ukraine",
          "USA | Austin, TX",
          "USA | Chicago",
          "USA | Colorado",
          "USA | Hawaii",
          "USA | Michigan",
          "USA | Minnesota",
          "USA | Nevada",
          "USA | New York City",
          "USA | Ohio",
          "USA | Utah",
          "USA | Vermont",
          "USA | Virginia",
          "USA | Washington",
          "USA",
          "Watches & Horology",
          "World",
        ],
      },
      {
        type: "checkboxgroup",
        messageKey: "UserSections",
        label: "Article Sections",
        defaultValue: [
          true, // Highlights
          true, // Quote
          true, // Perspectives
          true, // Historical Background
          true, // Humanitarian Impact
          true, // Technical Details
          true, // Scientific Significance
          true, // Travel Advisory
          true, // Performance Statistics
          true, // Industry Impact
          true, // Timeline
          true, // International Reactions
          true, // Quick Questions
          true, // Action items,
          true, // Did You Know?
        ],
        options: [
          "Highlights",
          "Quote",
          "Perspectives",
          "Historical Background",
          "Humanitarian Impact",
          "Technical Details",
          "Scientific Significance",
          "Travel Advisory",
          "Performance Statistics",
          "Industry Impact",
          "Timeline",
          "International Reactions",
          "Quick Questions",
          "Action items",
          "Did You Know?",
        ],
      },
      {
        type: "select",
        messageKey: "UserInterfaceLanguage",
        label: "Interface Language",
        defaultValue: "",
        description:
          "Changes the language of the app interface. Some languages may require additional language packs to display correctly.",
        options: [
          { label: "Default (System Language)", value: "" },
          { label: "English (English)", value: "en_US" },
          { label: "Español (Spanish)", value: "es_ES" },
          { label: "Français (French)", value: "fr_FR" },
          { label: "Deutsch (German)", value: "de_DE" },
          { label: "Italiano (Italian)", value: "it_IT" },
          { label: "Português (Portuguese)", value: "pt_PT" },
          { label: "Русский (Russian)", value: "ru_RU" },
          { label: "日本語 (Japanese)", value: "ja_JP" },
        ],
      },
      {
        type: "select",
        messageKey: "UserContentLanguage",
        label: "Content Language",
        defaultValue: "",
        description:
          "Changes the language of the news content. Not all languages may have full content available. Some languages may require additional language packs to display correctly.",
        options: [
          { label: "Default (Original Language)", value: "" },
          { label: "English (English)", value: "en" },
          { label: "Español (Spanish)", value: "es" },
          { label: "Français (French)", value: "fr" },
          { label: "Deutsch (German)", value: "de" },
          { label: "Italiano (Italian)", value: "it" },
          { label: "Português (Portuguese)", value: "pt" },
          {
            label: "Português Brasileiro (Brazilian Portuguese)",
            value: "pt-BR",
          },
          { label: "Русский (Russian)", value: "ru" },
          { label: "日本語 (Japanese)", value: "ja" },
        ],
      },
      {
        type: "slider",
        messageKey: "UserMaxStories",
        label: "Number of stories shown",
        defaultValue: 12,
        min: 3,
        max: 12,
        step: 1,
      },
      {
        type: "select",
        messageKey: "UserTextSize",
        label: "Text Size",
        defaultValue: "",
        options: [
          { label: "Default (Follow Notification Size)", value: "0" },
          { label: "Small", value: "1" },
          { label: "Medium", value: "2" },
          { label: "Large", value: "3" },
        ],
      },
      {
        type: "checkboxgroup",
        messageKey: "UserTimelinePins",
        label: "Timeline Pins",
        defaultValue: [false],
        options: ["Show news refresh time pins"],
      },
    ],
  },
  {
    type: "section",
    items: [
      {
        type: "heading",
        defaultValue: "Developer",
      },
      {
        type: "toggle",
        messageKey: "DebugMode",
        label: "Debug Mode",
        description: "Show notifications for warnings and errors",
        defaultValue: false,
      },
      {
        type: "checkboxgroup",
        messageKey: "ClearCacheOnSave",
        label: "Clear Cache On Save",
        defaultValue: [false, false, false],
        options: [
          "Clear full cache",
          "Clear timeline pin memory",
          "Clear read stories memory",
        ],
      },
    ],
  },
  {
    type: "submit",
    defaultValue: "Save",
  },
];
