export default [
  {
    type: "heading",
    defaultValue: "Settings",
  },
  {
    type: "section",
    items: [
      {
        type: "heading",
        defaultValue: "Categories",
      },
      {
        type: "checkboxgroup",
        messageKey: "UserCategories",
        label: "Categories",
        defaultValue: [
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          // false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
        ],
        options: [
          "AI",
          "Africa",
          "Apple",
          "Australia",
          "Austria",
          "Bay",
          "Belgium",
          "Bitcoin",
          "Brazil",
          "Business",
          "Canada",
          "Catholic",
          "China",
          "Coffee",
          "Colombia",
          "Costa Rica",
          "Croatia",
          "Cryptocurrency",
          "Cybersecurity",
          "Czech Republic",
          "Denmark",
          "Economy",
          "Estonia",
          "Europe",
          "Finland",
          "Formula 1",
          "France",
          "Gaming",
          "Germany | Hesse",
          "Germany",
          "Greece",
          "Hungary",
          "India",
          "Iran",
          "Ireland",
          "Israel",
          "Italy",
          "Japan",
          "Linux & OSS",
          "Lithuania",
          "Mexico",
          "Middle East",
          "NFL",
          "NHL",
          "New Zealand",
          "Nintendo",
          "Norway",
          "Pakistan",
          "Palestine",
          "Philippines",
          "Podcasting",
          "Poland",
          "Portugal",
          "Romania",
          "Russia",
          "Science",
          "Serbia",
          "Singapore",
          "Slovakia",
          "Slovenia",
          "South Korea",
          "Spain",
          "Sports",
          "Sweden",
          "Switzerland (DE)",
          "Switzerland (FR)",
          "Taiwan",
          "Technology",
          "Thailand",
          "The Netherlands",
          // "Today in History",
          "Turkey",
          "UK",
          "Ukraine",
          "USA | Austin, TX",
          "USA | Chicago",
          "USA | Colorado",
          "USA | Michigan",
          "USA | Minnesota",
          "USA | New York City",
          "USA | Ohio",
          "USA | Utah",
          "USA | Virginia",
          "USA",
          "iRacing & Sim Racing",
          "World",
        ],
      },
    ],
  },
  {
    type: "submit",
    defaultValue: "Save",
  },
];
