/*
 * This is an alphabetical list of all message keys used in the PKJS -> Watch communication.
 * IDs for these keys are automatically assigned by generate-message-keys.mjs, once added here.
 * This is redundant but it allows me to think less about key assignement and focus on names
 * without having to compromise on readability versus key management.
 */
module.exports = [
  "additionalFeedsCount",
  "articleDomain",
  "articleDomains",
  "availableDetailTypes",
  "categoryName",
  "categoryNamePage",
  "chunk",
  "detailContent",
  "detailContentType",
  "detailHasSources",
  "detailKey",
  "detailType",
  "error",
  "interfaceStrings",
  "isDebugMode",
  "loadingCurrent",
  "loadingMax",
  "logLevel",
  "logMessage",
  "logTag",
  "nextChunk",
  "nextPage",
  "page",
  "qrData",
  "qrSize",
  "sessionId",
  "shortData",
  "state",
  "storyId",
  "storyReadStatuses",
  "storySummary",
  "storyTitle",
  "storyTitles",
  "tensionIndex",
  "tensionReason",
  "textSize",
  "type",
];
