import { InterfaceStrings } from "../type";

export const strings: InterfaceStrings = {
  title: {
    category: "Kategorien",
    stories: "Geschichten",
    availableDetails: "Verfügbare Details",
  },
  section: {
    historicalBackground: "Historischer Hintergrund",
    humanitarianImpact: "Humanitäre Auswirkungen",
    didYouKnow: "Wussten Sie schon?",
    quote: "Zitat",
    highlights: "Höhepunkte",
    perspectives: "Perspektiven",
    quickQuestions: "Schnelle Fragen",
    technicalDetails: "Technische Details",
    industryImpact: "Auswirkungen auf die Branche",
    timeline: "Zeitleiste der Ereignisse",
    travelAdvisory: "Reisehinweis",
    internationalReactions: "Internationale Reaktionen",
    actionItems: "Aufgaben",
    scientificSignificance: "Wissenschaftliche Bedeutung",
    performanceStatistics: "Leistungsstatistik",
    sources: "Quellen",
  },
  category: {
    ai: "KI",
    africa: "Afrika",
    apple: "Apple",
    australia: "Australien",
    austria: "Österreich",
    bay: "USA | SF",
    belgium: "Belgien",
    bitcoin: "Bitcoin",
    brazil: "Brasilien",
    business: "Business",
    canada: "Kanada",
    catholic: "Katholisch",
    china: "China",
    coffee: "Kaffee",
    colombia: "Colombia",
    costa_rica: "Costa Rica",
    croatia: "Kroatien",
    cryptocurrency: "Kryptowährungen",
    cybersecurity: "Cybersicherheit",
    czech_republic: "Czech Republic",
    denmark: "Denmark",
    economy: "Wirtschaft",
    estonia: "Estland",
    europe: "Europa",
    finland: "Finnland",
    formula_1: "Formel 1",
    france: "Frankreich",
    gaming: "Gaming",
    germany_hesse: "Deutschland | Hessen",
    germany: "Deutschland",
    greece: "Griechenland",
    hungary: "Ungarn",
    india: "Indien",
    iran: "Iran",
    ireland: "Irland",
    israel: "Israel",
    italy: "Italien",
    japan: "Japan",
    linux_oss: "Linux & OSS",
    lithuania: "Litauen",
    mexico: "Mexiko",
    middle_east: "Middle East",
    nfl: "NFL",
    nhl: "NHL",
    new_zealand: "Neuseeland",
    nintendo: "Nintendo",
    norway: "Norway",
    pakistan: "Pakistan",
    palestine: "Palästina",
    philippines: "Philippines",
    podcasting: "Podcasting",
    poland: "Polen",
    portugal: "Portugal",
    romania: "Rumänien",
    russia: "Russia",
    science: "Wissenschaft",
    serbia: "Serbien",
    singapore: "Singapore",
    slovakia: "Slowakei",
    slovenia: "Slowenien",
    south_korea: "Südkorea",
    spain: "Spanien",
    sports: "Sport",
    sweden: "Schweden",
    switzerland_de: "Schweiz (DE)",
    switzerland_fr: "Schweiz (FR)",
    taiwan: "Taiwan",
    technology: "Technologie",
    thailand: "Thailand",
    the_netherlands: "Niederlande",
    turkey: "Turkey",
    uk: "Vereinigtes Königreich",
    ukraine: "Ukraine",
    usa_austin: "USA | Austin, TX",
    usa_chicago: "USA | Chicago",
    usa_colorado: "USA | Colorado",
    usa_michigan: "USA | Michigan",
    usa_minnesota: "USA | Minnesota",
    usa_nyc: "USA | New York City",
    usa_ohio: "USA | Ohio",
    usa_utah: "USA | Utah",
    usa_virginia: "USA | Virginia",
    usa: "USA",
    iracing: "iRacing & Sim Racing",
    world: "Welt",
  },
} as const;
