import { InterfaceStrings } from "../type";

export const strings: InterfaceStrings = {
  title: {
    category: "Categorías",
    stories: "Historias",
    availableDetails: "Detalles disponibles",
  },
  section: {
    historicalBackground: "Antecedentes Históricos",
    humanitarianImpact: "Impacto Humanitario",
    didYouKnow: "¿Sabías Que?",
    quote: "Cita",
    highlights: "Aspectos Destacados",
    perspectives: "Perspectivas",
    quickQuestions: "Preguntas Rápidas",
    technicalDetails: "Detalles Técnicos",
    industryImpact: "Impacto en la Industria",
    timeline: "Cronología",
    travelAdvisory: "Aviso de Viaje",
    internationalReactions: "Reacciones Internacionales",
    actionItems: "Puntos de Acción",
    scientificSignificance: "Relevancia Científica",
    performanceStatistics: "Estadísticas de Rendimiento",
    sources: "Fuentes",
  },
  category: {
    africa: "África",
    ai: "IA",
    apple: "Apple",
    argentina: "Argentina",
    australia: "Australia",
    austria: "Austria",
    bay: "Bahía",
    belgium: "Bélgica",
    bitcoin: "Bitcoin",
    brazil: "Brasil",
    business: "Negocios",
    canada: "Canadá",
    catholic: "Católico",
    china: "China",
    coffee: "Café",
    colombia: "Colombia",
    costa_rica: "Costa Rica",
    croatia: "Croacia",
    cryptocurrency: "Criptomonedas",
    cybersecurity: "Ciberseguridad",
    czech_republic: "República Checa",
    denmark: "Dinamarca",
    economy: "Economía",
    estonia: "Estonia",
    europe: "Europa",
    finland: "Finlandia",
    formula_1: "Fórmula 1",
    france: "Francia",
    french_music: "Música Francesa",
    gaming: "Videojuegos",
    germany_hesse: "Alemania | Hesse",
    germany: "Alemania",
    google: "Google",
    greece: "Grecia",
    healthcare_usa: "Salud en EE.UU.",
    hong_kong: "Hong Kong",
    hungary: "Hungría",
    india_tamil_nadu: "India | Tamil Nadu",
    india: "India",
    iracing: "iRacing y Sim Racing",
    iran: "Irán",
    ireland: "Irlanda",
    israel: "Israel",
    italy: "Italia",
    japan: "Japón",
    linux_oss: "Linux y Código Abierto",
    lithuania: "Lituania",
    mexico: "México",
    microsoft: "Microsoft",
    new_zealand: "Nueva Zelanda",
    nfl: "NFL",
    nhl: "NHL",
    nintendo: "Nintendo",
    norway: "Noruega",
    pakistan: "Pakistán",
    palestine: "Palestina",
    philippines: "Filipinas",
    podcasting: "Podcasting",
    poland: "Polonia",
    portugal: "Portugal",
    privacy: "Privacidad",
    romania: "Rumanía",
    russia: "Rusia",
    science: "Ciencia",
    serbia: "Serbia",
    simulation_games: "Juegos de Simulación",
    singapore: "Singapur",
    slovakia: "Eslovaquia",
    slovenia: "Eslovenia",
    south_korea: "Corea del Sur",
    spain: "España",
    sports: "Deportes",
    sweden: "Suecia",
    switzerland_de: "Suiza (DE)",
    switzerland_fr: "Suiza (FR)",
    taiwan: "Taiwán",
    technology: "Tecnología",
    thailand: "Tailandia",
    the_netherlands: "Países Bajos",
    three_d_printing: "Impresión 3D",
    turkey: "Turquía",
    uk: "Reino Unido",
    ukraine: "Ucrania",
    usa_austin: "EE. UU. | Austin, TX",
    usa_chicago: "EE. UU. | Chicago",
    usa_colorado: "EE. UU. | Colorado",
    usa_hawaii: "EE.UU. | Hawái",
    usa_michigan: "EE. UU. | Míchigan",
    usa_minnesota: "EE. UU. | Minnesota",
    usa_nevada: "EE.UU. | Nevada",
    usa_nyc: "EE. UU. | Nueva York",
    usa_ohio: "EE. UU. | Ohio",
    usa_utah: "EE. UU. | Utah",
    usa_vermont: "EE.UU. | Vermont",
    usa_virginia: "EE. UU. | Virginia",
    usa_washington: "EE.UU. | Washington",
    usa: "EE. UU.",
    watches_and_horology: "Relojes y Relojería",
    world: "Mundo",
  },
} as const;
