import { InterfaceStrings } from "../type";

export const strings: InterfaceStrings = {
  title: {
    category: "Categorías",
    stories: "Historias",
    availableDetails: "Detalles disponibles",
  },
  section: {
    historicalBackground: "Antecedentes históricos",
    humanitarianImpact: "Impacto humanitario",
    didYouKnow: "¿Sabías que?",
    quote: "Cita",
    highlights: "Aspectos destacados",
    perspectives: "Perspectivas",
    quickQuestions: "Preguntas rápidas",
    technicalDetails: "Detalles técnicos",
    industryImpact: "Impacto en la industria",
    timeline: "Cronología de eventos",
    travelAdvisory: "Aviso de viaje",
    internationalReactions: "Reacciones internacionales",
    actionItems: "Puntos de acción",
    scientificSignificance: "Relevancia científica",
    performanceStatistics: "Estadísticas de rendimiento",
    sources: "Fuentes",
  },
  category: {
    ai: "IA",
    africa: "África",
    apple: "Apple",
    australia: "Australia",
    austria: "Austria",
    bay: "USA Bahía",
    belgium: "Bélgica",
    bitcoin: "Bitcoin",
    brazil: "Brasil",
    business: "Negocios",
    canada: "Canadá",
    catholic: "Católico",
    china: "China",
    coffee: "Café",
    colombia: "Colombia",
    costa_rica: "Costa Rica",
    croatia: "Croacia",
    cryptocurrency: "Criptomonedas",
    cybersecurity: "Ciberseguridad",
    czech_republic: "Czech Republic",
    denmark: "Denmark",
    economy: "Economía",
    estonia: "Estonia",
    europe: "Europa",
    finland: "Finlandia",
    formula_1: "Fórmula 1",
    france: "Francia",
    gaming: "Videojuegos",
    germany_hesse: "Alemania | Hesse",
    germany: "Alemania",
    greece: "Grecia",
    hungary: "Hungría",
    india: "India",
    iran: "Irán",
    ireland: "Irlanda",
    israel: "Israel",
    italy: "Italia",
    japan: "Japón",
    linux_oss: "Linux y Código Abierto",
    lithuania: "Lituania",
    mexico: "México",
    middle_east: "Medio Oriente",
    nfl: "NFL",
    nhl: "NHL",
    new_zealand: "Nueva Zelanda",
    nintendo: "Nintendo",
    norway: "Noruega",
    pakistan: "Pakistán",
    palestine: "Palestina",
    philippines: "Filipinas",
    podcasting: "Podcasting",
    poland: "Polonia",
    portugal: "Portugal",
    romania: "Rumanía",
    russia: "Russia",
    science: "Ciencia",
    serbia: "Serbia",
    singapore: "Singapore",
    slovakia: "Eslovaquia",
    slovenia: "Eslovenia",
    south_korea: "Corea del Sur",
    spain: "España",
    sports: "Deportes",
    sweden: "Suecia",
    switzerland_de: "Suiza (DE)",
    switzerland_fr: "Suiza (FR)",
    taiwan: "Taiwán",
    technology: "Tecnología",
    thailand: "Tailandia",
    the_netherlands: "Países Bajos",
    turkey: "Turkey",
    uk: "Reino Unido",
    ukraine: "Ucrania",
    usa_austin: "EE. UU. | Austin, TX",
    usa_chicago: "EE. UU. | Chicago",
    usa_colorado: "EE. UU. | Colorado",
    usa_michigan: "EE. UU. | Míchigan",
    usa_minnesota: "EE. UU. | Minnesota",
    usa_nyc: "EE. UU. | Nueva York",
    usa_ohio: "EE. UU. | Ohio",
    usa_utah: "EE. UU. | Utah",
    usa_virginia: "EE. UU. | Virginia",
    usa: "EE. UU.",
    iracing: "iRacing y Sim Racing",
    world: "Mundo",
  },
} as const;
