import { InterfaceStrings } from "../type";

export const strings: InterfaceStrings = {
  title: {
    category: "Catégories",
    stories: "Histoires",
    availableDetails: "Détails disponibles",
  },
  section: {
    historicalBackground: "Contexte historique",
    humanitarianImpact: "Impact humanitaire",
    didYouKnow: "Le saviez-vous ?",
    quote: "Citation",
    highlights: "Faits saillants",
    perspectives: "Perspectives",
    quickQuestions: "Questions rapides",
    technicalDetails: "Détails techniques",
    industryImpact: "Impact sur l'industrie",
    timeline: "Chronologie",
    travelAdvisory: "Avis aux voyageurs",
    internationalReactions: "Réactions internationales",
    actionItems: "Actions à mener",
    scientificSignificance: "Importance scientifique",
    performanceStatistics: "Statistiques de performance",
    sources: "Sources",
  },
  category: {
    ai: "IA",
    africa: "Afrique",
    apple: "Apple",
    australia: "Australie",
    austria: "Autriche",
    bay: "USA | SF",
    belgium: "Belgique",
    bitcoin: "Bitcoin",
    brazil: "Brésil",
    business: "Affaires",
    canada: "Canada",
    catholic: "Catholique",
    china: "Chine",
    coffee: "Café",
    colombia: "Colombia",
    costa_rica: "Costa Rica",
    croatia: "Croatie",
    cryptocurrency: "Cryptomonnaies",
    cybersecurity: "Cybersécurité",
    czech_republic: "Czech Republic",
    denmark: "Denmark",
    economy: "Économie",
    estonia: "Estonie",
    europe: "Europe",
    finland: "Finland",
    formula_1: "Formule 1",
    france: "France",
    gaming: "Jeux vidéo",
    germany_hesse: "Allemagne | Hesse",
    germany: "Allemagne",
    greece: "Grèce",
    hungary: "Hongrie",
    india: "Inde",
    iran: "Iran",
    ireland: "Irlande",
    israel: "Israël",
    italy: "Italie",
    japan: "Japon",
    linux_oss: "Linux et Open Source",
    lithuania: "Lituanie",
    mexico: "Mexique",
    middle_east: "Middle East",
    nfl: "NFL",
    nhl: "LNH",
    new_zealand: "Nouvelle-Zélande",
    nintendo: "Nintendo",
    norway: "Norway",
    pakistan: "Pakistan",
    palestine: "Palestine",
    philippines: "Philippines",
    podcasting: "Podcasting",
    poland: "Pologne",
    portugal: "Portugal",
    romania: "Roumanie",
    russia: "Russia",
    science: "Science",
    serbia: "Serbie",
    singapore: "Singapore",
    slovakia: "Slovaquie",
    slovenia: "Slovénie",
    south_korea: "Corée du Sud",
    spain: "Espagne",
    sports: "Sports",
    sweden: "Suède",
    switzerland_de: "Suisse (DE)",
    switzerland_fr: "Suisse (FR)",
    taiwan: "Taïwan",
    technology: "Technologie",
    thailand: "Thaïlande",
    the_netherlands: "Pays-Bas",
    turkey: "Turkey",
    uk: "Royaume-Uni",
    ukraine: "Ukraine",
    usa_austin: "États-Unis | Austin, TX",
    usa_chicago: "États-Unis | Chicago",
    usa_colorado: "États-Unis | Colorado",
    usa_michigan: "États-Unis | Michigan",
    usa_minnesota: "États-Unis | Minnesota",
    usa_nyc: "États-Unis | New York",
    usa_ohio: "États-Unis | Ohio",
    usa_utah: "États-Unis | Utah",
    usa_virginia: "États-Unis | Virginie",
    usa: "États-Unis",
    iracing: "iRacing et Sim Racing",
    world: "Monde",
  },
} as const;
