import { InterfaceStrings } from "../type";

export const strings: InterfaceStrings = {
  title: {
    category: "Categorie",
    stories: "Storie",
    availableDetails: "Dettagli disponibili",
  },
  section: {
    historicalBackground: "Contesto storico",
    humanitarianImpact: "Impatto umanitario",
    didYouKnow: "Lo sapevi?",
    quote: "Citazione",
    highlights: "Punti salienti",
    perspectives: "Prospettive",
    quickQuestions: "Domande rapide",
    technicalDetails: "Dettagli tecnici",
    industryImpact: "Impatto sul settore",
    timeline: "Cronologia",
    travelAdvisory: "Avviso di viaggio",
    internationalReactions: "Reazioni internazionali",
    actionItems: "Punti d'azione",
    scientificSignificance: "Importanza scientifica",
    performanceStatistics: "Statistiche delle prestazioni",
    sources: "Fonti",
  },
  category: {
    ai: "IA",
    africa: "Africa",
    apple: "Apple",
    australia: "Australia",
    austria: "Austria",
    bay: "USA SF",
    belgium: "Belgio",
    bitcoin: "Bitcoin",
    brazil: "Brasile",
    business: "Economia",
    canada: "Canada",
    catholic: "Cattolico",
    china: "China",
    coffee: "Caffè",
    colombia: "Colombia",
    costa_rica: "Costa Rica",
    croatia: "Croazia",
    cryptocurrency: "Criptovalute",
    cybersecurity: "Sicurezza informatica",
    czech_republic: "Czech Republic",
    denmark: "Denmark",
    economy: "Economia",
    estonia: "Estonia",
    europe: "Europa",
    finland: "Finland",
    formula_1: "Formula 1",
    france: "Francia",
    gaming: "Videogiochi",
    germany_hesse: "Germania | Assia",
    germany: "Germania",
    greece: "Grecia",
    hungary: "Ungheria",
    india: "India",
    iran: "Iran",
    ireland: "Irlanda",
    israel: "Israele",
    italy: "Italia",
    japan: "Giappone",
    linux_oss: "Linux e Open Source",
    lithuania: "Lituania",
    mexico: "Messico",
    middle_east: "Middle East",
    nfl: "NFL",
    nhl: "NHL",
    new_zealand: "Nuova Zelanda",
    nintendo: "Nintendo",
    norway: "Norway",
    pakistan: "Pakistan",
    palestine: "Palestina",
    philippines: "Philippines",
    podcasting: "Podcasting",
    poland: "Polonia",
    portugal: "Portogallo",
    romania: "Romania",
    russia: "Russia",
    science: "Scienza",
    serbia: "Serbia",
    singapore: "Singapore",
    slovakia: "Slovacchia",
    slovenia: "Slovenia",
    south_korea: "Corea del Sud",
    spain: "Spagna",
    sports: "Sport",
    sweden: "Svezia",
    switzerland_de: "Svizzera (DE)",
    switzerland_fr: "Svizzera (FR)",
    taiwan: "Taiwan",
    technology: "Tecnologia",
    thailand: "Thailandia",
    the_netherlands: "Paesi Bassi",
    turkey: "Turkey",
    uk: "Regno Unito",
    ukraine: "Ucraina",
    usa_austin: "USA | Austin, TX",
    usa_chicago: "USA | Chicago",
    usa_colorado: "USA | Colorado",
    usa_michigan: "USA | Michigan",
    usa_minnesota: "USA | Minnesota",
    usa_nyc: "USA | New York City",
    usa_ohio: "USA | Ohio",
    usa_utah: "USA | Utah",
    usa_virginia: "USA | Virginia",
    usa: "USA",
    iracing: "iRacing e Sim Racing",
    world: "Mondo",
  },
} as const;
