import { InterfaceStrings } from "../type";

export const strings: InterfaceStrings = {
  title: {
    category: "Categorias",
    stories: "Histórias",
    availableDetails: "Detalhes disponíveis",
  },
  section: {
    historicalBackground: "Contexto histórico",
    humanitarianImpact: "Impacto humanitário",
    didYouKnow: "Você sabia?",
    quote: "Citação",
    highlights: "Destaques",
    perspectives: "Perspectivas",
    quickQuestions: "Perguntas rápidas",
    technicalDetails: "Detalhes técnicos",
    industryImpact: "Impacto na indústria",
    timeline: "Linha do tempo",
    travelAdvisory: "Aviso de viagem",
    internationalReactions: "Reações internacionais",
    actionItems: "Itens de ação",
    scientificSignificance: "Importância científica",
    performanceStatistics: "Estatísticas de desempenho",
    sources: "Fontes",
  },
  category: {
    ai: "IA",
    africa: "África",
    apple: "Apple",
    australia: "Austrália",
    austria: "Áustria",
    bay: "EUA Baía",
    belgium: "Bélgica",
    bitcoin: "Bitcoin",
    brazil: "Brasil",
    business: "Negócios",
    canada: "Canadá",
    catholic: "Católico",
    china: "China",
    coffee: "Café",
    colombia: "Colômbia",
    costa_rica: "Costa Rica",
    croatia: "Croácia",
    cryptocurrency: "Criptomoedas",
    cybersecurity: "Cibersegurança",
    czech_republic: "Czech Republic",
    denmark: "Denmark",
    economy: "Economia",
    estonia: "Estônia",
    europe: "Europa",
    finland: "Finland",
    formula_1: "Fórmula 1",
    france: "França",
    gaming: "Jogos",
    germany_hesse: "Alemanha | Hesse",
    germany: "Alemanha",
    greece: "Grécia",
    hungary: "Hungria",
    india: "Índia",
    iran: "Irã",
    ireland: "Irlanda",
    israel: "Israel",
    italy: "Itália",
    japan: "Japão",
    linux_oss: "Linux e Código Aberto",
    lithuania: "Lituânia",
    mexico: "México",
    middle_east: "Middle East",
    nfl: "NFL",
    nhl: "NHL",
    new_zealand: "Nova Zelândia",
    nintendo: "Nintendo",
    norway: "Norway",
    pakistan: "Paquistão",
    palestine: "Palestina",
    philippines: "Philippines",
    podcasting: "Podcasting",
    poland: "Polônia",
    portugal: "Portugal",
    romania: "Romênia",
    russia: "Russia",
    science: "Ciência",
    serbia: "Sérvia",
    singapore: "Singapore",
    slovakia: "Eslováquia",
    slovenia: "Eslovênia",
    south_korea: "Coreia do Sul",
    spain: "Espanha",
    sports: "Esportes",
    sweden: "Suécia",
    switzerland_de: "Suíça (DE)",
    switzerland_fr: "Suíça (FR)",
    taiwan: "Taiwan",
    technology: "Tecnologia",
    thailand: "Tailândia",
    the_netherlands: "Países Baixos",
    turkey: "Turkey",
    uk: "Reino Unido",
    ukraine: "Ucrânia",
    usa_austin: "EUA | Austin, TX",
    usa_chicago: "EUA | Chicago",
    usa_colorado: "EUA | Colorado",
    usa_michigan: "EUA | Michigan",
    usa_minnesota: "EUA | Minnesota",
    usa_nyc: "EUA | New York",
    usa_ohio: "EUA | Ohio",
    usa_utah: "EUA | Utah",
    usa_virginia: "EUA | Virgínia",
    usa: "EUA",
    iracing: "iRacing e Sim Racing",
    world: "Mundo",
  },
} as const;
