#pragma once

// String identifiers for all translatable strings in the app

typedef enum
{
    // General
    STRING_LOADING,
    // Main menu
    STRING_FEEDS,
    STRING_NEWS,
    STRING_CATEGORIES,
    STRING_STORIES,
    STRING_AVAILABLE_DETAILS,
    // Detail type display names
    STRING_HISTORICAL_BACKGROUND,
    STRING_HUMANITARIAN_IMPACT,
    STRING_DID_YOU_KNOW,
    STRING_QUOTE,
    STRING_HIGHLIGHTS,
    STRING_PERSPECTIVES,
    STRING_QUICK_QUESTIONS,
    STRING_TECHNICAL_DETAILS,
    STRING_INDUSTRY_IMPACT,
    STRING_TIMELINE,
    STRING_TRAVEL_ADVISORY,
    STRING_INTERNATIONAL_REACTIONS,
    STRING_ACTION_ITEMS,
    STRING_SCIENTIFIC_SIGNIFICANCE,
    STRING_PERFORMANCE_STATISTICS,
    STRING_SOURCES,
    // Generic category slots (up to 20 categories)
    STRING_CATEGORY_A,
    STRING_CATEGORY_B,
    STRING_CATEGORY_C,
    STRING_CATEGORY_D,
    STRING_CATEGORY_E,
    STRING_CATEGORY_F,
    STRING_CATEGORY_G,
    STRING_CATEGORY_H,
    STRING_CATEGORY_I,
    STRING_CATEGORY_J,
    STRING_CATEGORY_K,
    STRING_CATEGORY_L,
    STRING_CATEGORY_M,
    STRING_CATEGORY_N,
    STRING_CATEGORY_O,
    STRING_CATEGORY_P,
    STRING_CATEGORY_Q,
    STRING_CATEGORY_R,
    STRING_CATEGORY_S,
    STRING_CATEGORY_T,
    STRING_COUNT
} StringId;