import { InterfaceStrings } from "../type";

export const strings: InterfaceStrings = {
  general: {
    loading: "Loading...",
  },
  title: {
    feeds: "Feeds",
    news: "News",
    category: "Categories",
    stories: "Stories",
    availableDetails: "Available Details",
  },
  section: {
    historicalBackground: "Historical Background",
    humanitarianImpact: "Humanitarian Impact",
    didYouKnow: "Did You Know?",
    quote: "Quote",
    highlights: "Highlights",
    perspectives: "Perspectives",
    quickQuestions: "Quick Questions",
    technicalDetails: "Technical Details",
    industryImpact: "Industry Impact",
    timeline: "Timeline",
    travelAdvisory: "Travel Advisory",
    internationalReactions: "International Reactions",
    actionItems: "Action Items",
    scientificSignificance: "Scientific Significance",
    performanceStatistics: "Performance Statistics",
    sources: "Sources",
  },
  category: {
    africa: "Africa",
    ai: "AI",
    apple: "Apple",
    argentina: "Argentina",
    australia: "Australia",
    austria: "Austria",
    bay: "Bay",
    belgium: "Belgium",
    bitcoin: "Bitcoin",
    brazil: "Brazil",
    business: "Business",
    canada: "Canada",
    catholic: "Catholic",
    china: "China",
    coffee: "Coffee",
    colombia: "Colombia",
    costa_rica: "Costa Rica",
    croatia: "Croatia",
    cryptocurrency: "Cryptocurrency",
    cybersecurity: "Cybersecurity",
    czech_republic: "Czech Republic",
    denmark: "Denmark",
    economy: "Economy",
    estonia: "Estonia",
    europe: "Europe",
    finland: "Finland",
    formula_1: "Formula 1",
    france: "France",
    french_music: "French Music",
    gaming: "Gaming",
    germany_hesse: "Germany | Hesse",
    germany: "Germany",
    google: "Google",
    greece: "Greece",
    healthcare_usa: "Healthcare | USA",
    hong_kong: "Hong Kong",
    hungary: "Hungary",
    india_tamil_nadu: "India | Tamil Nadu",
    india: "India",
    iracing: "iRacing & Sim Racing",
    iran: "Iran",
    ireland: "Ireland",
    israel: "Israel",
    italy: "Italy",
    japan: "Japan",
    linux_oss: "Linux & OSS",
    lithuania: "Lithuania",
    mexico: "Mexico",
    microsoft: "Microsoft",
    new_zealand: "New Zealand",
    nfl: "NFL",
    nhl: "NHL",
    nintendo: "Nintendo",
    norway: "Norway",
    pakistan: "Pakistan",
    palestine: "Palestine",
    philippines: "Philippines",
    podcasting: "Podcasting",
    poland: "Poland",
    portugal: "Portugal",
    privacy: "Privacy",
    romania: "Romania",
    russia: "Russia",
    science: "Science",
    serbia: "Serbia",
    simulation_games: "Simulation Games",
    singapore: "Singapore",
    slovakia: "Slovakia",
    slovenia: "Slovenia",
    south_korea: "South Korea",
    spain: "Spain",
    sports: "Sports",
    sweden: "Sweden",
    switzerland_de: "Switzerland (DE)",
    switzerland_fr: "Switzerland (FR)",
    taiwan: "Taiwan",
    technology: "Technology",
    thailand: "Thailand",
    the_netherlands: "The Netherlands",
    three_d_printing: "3D Printing",
    turkey: "Turkey",
    uk: "UK",
    ukraine: "Ukraine",
    usa_austin: "USA | Austin, TX",
    usa_chicago: "USA | Chicago",
    usa_colorado: "USA | Colorado",
    usa_hawaii: "USA | Hawaii",
    usa_michigan: "USA | Michigan",
    usa_minnesota: "USA | Minnesota",
    usa_nevada: "USA | Nevada",
    usa_nyc: "USA | New York City",
    usa_ohio: "USA | Ohio",
    usa_utah: "USA | Utah",
    usa_vermont: "USA | Vermont",
    usa_virginia: "USA | Virginia",
    usa_washington: "USA | Washington",
    usa: "USA",
    watches_and_horology: "Watches & Horology",
    world: "World",
  },
  feature: {
    small_web_feed: "Small Web",
  },
} as const;
