import { InterfaceStrings } from "../type";

export const strings: InterfaceStrings = {
  general: {
    loading: "Loading...",
    tensionIndex: "World Tension",
    tensionIndexShort: "Tension",
    tensionIndexExplanationTitle: "What is World Tension?",
    tensionIndexLevel1: "0-20° Cool - Calm period, routine activity",
    tensionIndexLevel2: "21-40° Mild - Normal global tensions",
    tensionIndexLevel3: "41-60° Warm - Elevated concerns",
    tensionIndexLevel4: "61-80° Hot - Serious situations",
    tensionIndexLevel5: "81-100° Critical - Extreme crisis",
    tensionIndexExplanation:
      "This World Tension index is generated by AI analysis of current world news headlines. It is not meant to raise alarm but to provide a general snapshot of global tensions to consider when viewing news stories.",
  },
  title: {
    feeds: "Feeds",
    news: "News",
    category: "Categories",
    stories: "Stories",
    availableDetails: "Available Details",
  },
  section: {
    historicalBackground: "Historical Background",
    humanitarianImpact: "Humanitarian Impact",
    didYouKnow: "Did You Know?",
    quote: "Quote",
    highlights: "Highlights",
    perspectives: "Perspectives",
    quickQuestions: "Quick Questions",
    technicalDetails: "Technical Details",
    industryImpact: "Industry Impact",
    timeline: "Timeline",
    travelAdvisory: "Travel Advisory",
    internationalReactions: "International Reactions",
    actionItems: "Action Items",
    scientificSignificance: "Scientific Significance",
    performanceStatistics: "Performance Statistics",
    sources: "Sources",
  },
  category: {
    World: "World",
    USA: "USA",
    Business: "Business",
    Technology: "Technology",
    Science: "Science",
    Sports: "Sports",
    Gaming: "Gaming",
  },
  feature: {
    small_web_feed: "Small Web",
  },
} as const;
