import { InterfaceStrings } from "../type";

export const strings: InterfaceStrings = {
  general: {
    loading: "Laden...",
  },
  title: {
    feeds: "Feeds",
    news: "Nachrichten",
    category: "Kategorien",
    stories: "Geschichten",
    availableDetails: "Verfügbare Details",
  },
  section: {
    historicalBackground: "Historischer Hintergrund",
    humanitarianImpact: "Humanitäre Auswirkungen",
    didYouKnow: "Wussten Sie Schon?",
    quote: "Zitat",
    highlights: "Höhepunkte",
    perspectives: "Perspektiven",
    quickQuestions: "Schnelle Fragen",
    technicalDetails: "Technische Details",
    industryImpact: "Auswirkungen auf die Branche",
    timeline: "Zeitleiste",
    travelAdvisory: "Reisehinweis",
    internationalReactions: "Internationale Reaktionen",
    actionItems: "Aufgaben",
    scientificSignificance: "Wissenschaftliche Bedeutung",
    performanceStatistics: "Leistungsstatistik",
    sources: "Quellen",
  },
  category: {
    africa: "Afrika",
    ai: "KI",
    apple: "Apple",
    argentina: "Argentinien",
    asia: "Asien",
    australia: "Australien",
    austria: "Österreich",
    bay_area: "Bay Area",
    belgium: "Belgien",
    bitcoin: "Bitcoin",
    brazil: "Brasilien",
    business: "Business",
    canada: "Kanada",
    catholic: "Katholisch",
    china: "China",
    climate_change: "Klimawandel",
    colombia: "Kolumbien",
    costa_rica: "Costa Rica",
    croatia: "Kroatien",
    cryptocurrency: "Kryptowährung",
    cybersecurity: "Cybersicherheit",
    cycling: "Radfahren",
    czech_republic: "Tschechische Republik",
    defense: "Verteidigung",
    denmark: "Dänemark",
    economy: "Wirtschaft",
    estonia: "Estland",
    europe: "Europa",
    finland_helsinki: "Finnland | Helsinki",
    finland: "Finnland",
    formula_1: "Formel 1",
    france: "Frankreich",
    french_music: "Französische Musik",
    gaming: "Gaming",
    germany_badenwurttemberg: "Deutschland | Baden-Württemberg",
    germany_hamburg: "Deutschland | Hamburg",
    germany_hesse: "Deutschland | Hessen",
    germany: "Deutschland",
    google: "Google",
    greece: "Griechenland",
    healthcare_usa: "Gesundheitswesen | USA",
    hong_kong: "Hongkong",
    hungary: "Ungarn",
    india: "Indien",
    iran: "Iran",
    ireland: "Irland",
    israel: "Israel",
    italy: "Italien",
    japan: "Japan",
    linux_oss: "Linux & OSS",
    lithuania: "Litauen",
    metal_music: "Metal Musik",
    mexico: "Mexiko",
    microsoft: "Microsoft",
    middle_east: "Mittlerer Osten",
    mlb: "MLB",
    mma: "MMA",
    morocco: "Marokko",
    movies: "Filme",
    music: "Musik",
    new_zealand: "Neuseeland",
    nfl: "NFL",
    nhl: "NHL",
    nintendo: "Nintendo",
    north_macedonia: "Nordmazedonien",
    norway: "Norwegen",
    pakistan: "Pakistan",
    palestine: "Palästina",
    philippines: "Philippinen",
    podcasting: "Podcasting",
    poland: "Polen",
    portugal: "Portugal",
    privacy: "Datenschutz",
    professional_wrestling: "Professionelles Wrestling",
    romania: "Rumänien",
    russia: "Russland",
    science: "Wissenschaft",
    serbia: "Serbien",
    simulation_games: "Simulationsspiele",
    singapore: "Singapur",
    slovakia: "Slowakei",
    slovenia: "Slowenien",
    south_korea: "Südkorea",
    spain: "Spanien",
    sports: "Sport",
    sweden: "Schweden",
    switzerland_de: "Schweiz (DE)",
    switzerland_fr: "Schweiz (FR)",
    switzerland_it: "Schweiz (IT)",
    taiwan: "Taiwan",
    technology: "Technologie",
    thailand: "Thailand",
    the_netherlands: "Niederlande",
    three_d_printing: "Additive Fertigung",
    turkey: "Türkei",
    uk: "Vereinigtes Königreich",
    ukraine: "Ukraine",
    us_soccer: "U.S. Soccer",
    usa_boston: "USA | Boston",
    usa_chicago: "USA | Chicago",
    usa_colorado: "USA | Colorado",
    usa_florida: "USA | Florida",
    usa_michigan: "USA | Michigan",
    usa_minnesota: "USA | Minnesota",
    usa_nevada: "USA | Nevada",
    usa_new_mexico: "USA | New Mexico",
    usa_nyc: "USA | New York City",
    usa_ohio: "USA | Ohio",
    usa_oregon: "USA | Oregon",
    usa_utah: "USA | Utah",
    usa_vermont: "USA | Vermont",
    usa_virginia: "USA | Virginia",
    usa_washington: "USA | Washington",
    usa: "USA",
    venezuela: "Venezuela",
    watches_and_horology: "Uhren & Uhrmacherkunst",
    world: "Welt",
  },
  feature: {
    small_web_feed: "Kleiner Web",
  },
} as const;
