import { InterfaceStrings } from "../type";

export const strings: InterfaceStrings = {
  general: {
    loading: "Cargando...",
    tensionIndex: "Tensión Mundial",
    tensionIndexShort: "Tensión",
    tensionIndexExplanationTitle: "¿Qué es la Tensión Mundial?",
    tensionIndexLevel1: "0-20° Fresco - Período de calma, actividad rutinaria",
    tensionIndexLevel2: "21-40° Suave - Tensiones globales normales",
    tensionIndexLevel3: "41-60° Cálido - Preocupaciones elevadas",
    tensionIndexLevel4: "61-80° Caliente - Situaciones serias",
    tensionIndexLevel5: "81-100° Crítico - Crisis extrema",
    tensionIndexExplanation:
      "Este índice de Tensión Mundial se genera mediante análisis de IA de los titulares de noticias mundiales actuales. No está destinado a generar alarma, sino a proporcionar una instantánea general de las tensiones globales para considerar al ver las historias de noticias.",
  },
  title: {
    feeds: "Fuentes",
    news: "Noticias",
    category: "Categorías",
    stories: "Historias",
    availableDetails: "Detalles disponibles",
  },
  section: {
    historicalBackground: "Antecedentes Históricos",
    humanitarianImpact: "Impacto Humanitario",
    didYouKnow: "¿Sabías Que?",
    quote: "Cita",
    highlights: "Aspectos Destacados",
    perspectives: "Perspectivas",
    quickQuestions: "Preguntas Rápidas",
    technicalDetails: "Detalles Técnicos",
    industryImpact: "Impacto en la Industria",
    timeline: "Cronología",
    travelAdvisory: "Aviso de Viaje",
    internationalReactions: "Reacciones Internacionales",
    actionItems: "Puntos de Acción",
    scientificSignificance: "Relevancia Científica",
    performanceStatistics: "Estadísticas de Rendimiento",
    sources: "Fuentes",
  },
  category: {
    africa: "África",
    ai: "IA",
    apple: "Apple",
    argentina: "Argentina",
    asia: "Asia",
    australia: "Australia",
    austria: "Austria",
    bay_area: "EE. UU. | Área de la Bahía",
    belgium: "Bélgica",
    bitcoin: "Bitcoin",
    brazil: "Brasil",
    business: "Negocios",
    canada: "Canadá",
    catholic: "Católico",
    china: "China",
    climate_change: "Cambio Climático",
    colombia: "Colombia",
    costa_rica: "Costa Rica",
    croatia: "Croacia",
    cryptocurrency: "Criptomonedas",
    cybersecurity: "Ciberseguridad",
    cycling: "Ciclismo",
    czech_republic: "República Checa",
    defense: "Defensa",
    denmark: "Dinamarca",
    economy: "Economía",
    estonia: "Estonia",
    europe: "Europa",
    finland_helsinki: "Finlandia | Helsinki",
    finland: "Finlandia",
    formula_1: "Fórmula 1",
    france: "Francia",
    french_music: "Música Francesa",
    gaming: "Videojuegos",
    germany_badenwurttemberg: "Alemania | Baden-Wurtemberg",
    germany_hamburg: "Alemania | Hamburgo",
    germany_hesse: "Alemania | Hesse",
    germany: "Alemania",
    google: "Google",
    greece: "Grecia",
    healthcare_usa: "Salud en EE.UU.",
    hong_kong: "Hong Kong",
    hungary: "Hungría",
    india: "India",
    iran: "Irán",
    ireland: "Irlanda",
    israel: "Israel",
    italy: "Italia",
    japan: "Japón",
    linux_oss: "Linux y Código Abierto",
    lithuania: "Lituania",
    metal_music: "Música Metal",
    mexico: "México",
    microsoft: "Microsoft",
    middle_east: "Oriente Medio",
    mlb: "MLB",
    mma: "MMA",
    morocco: "Marruecos",
    movies: "Cine",
    music: "Música",
    new_zealand: "Nueva Zelanda",
    nfl: "NFL",
    nhl: "NHL",
    nintendo: "Nintendo",
    north_macedonia: "Macedonia del Norte",
    norway: "Noruega",
    pakistan: "Pakistán",
    palestine: "Palestina",
    philippines: "Filipinas",
    podcasting: "Podcasting",
    poland: "Polonia",
    portugal: "Portugal",
    privacy: "Privacidad",
    professional_wrestling: "Lucha Libre Profesional",
    romania: "Rumanía",
    russia: "Rusia",
    science: "Ciencia",
    serbia: "Serbia",
    simulation_games: "Juegos de Simulación",
    singapore: "Singapur",
    slovakia: "Eslovaquia",
    slovenia: "Eslovenia",
    south_korea: "Corea del Sur",
    spain: "España",
    sports: "Deportes",
    sweden: "Suecia",
    switzerland_de: "Suiza (DE)",
    switzerland_fr: "Suiza (FR)",
    switzerland_it: "Suiza (IT)",
    taiwan: "Taiwán",
    technology: "Tecnología",
    thailand: "Tailandia",
    the_netherlands: "Países Bajos",
    three_d_printing: "Impresión 3D",
    turkey: "Turquía",
    uk: "Reino Unido",
    ukraine: "Ucrania",
    us_soccer: "Fútbol de EE. UU.",
    usa_boston: "EE. UU. | Boston",
    usa_chicago: "EE. UU. | Chicago",
    usa_colorado: "EE. UU. | Colorado",
    usa_florida: "EE. UU. | Florida",
    usa_michigan: "EE. UU. | Míchigan",
    usa_minnesota: "EE. UU. | Minnesota",
    usa_nevada: "EE.UU. | Nevada",
    usa_new_mexico: "EE. UU. | Nuevo México",
    usa_nyc: "EE. UU. | Nueva York",
    usa_ohio: "EE. UU. | Ohio",
    usa_oregon: "EE. UU. | Oregón",
    usa_utah: "EE. UU. | Utah",
    usa_vermont: "EE.UU. | Vermont",
    usa_virginia: "EE. UU. | Virginia",
    usa_washington: "EE.UU. | Washington",
    usa: "EE. UU.",
    venezuela: "Venezuela",
    watches_and_horology: "Relojes y Relojería",
    world: "Mundo",
  },
  feature: {
    small_web_feed: "Pequeña Fuente",
  },
} as const;
