import { InterfaceStrings } from "../type";

export const strings: InterfaceStrings = {
  title: {
    category: "Catégories",
    stories: "Histoires",
    availableDetails: "Détails disponibles",
  },
  section: {
    historicalBackground: "Contexte Historique",
    humanitarianImpact: "Impact Humanitaire",
    didYouKnow: "Le Saviez-Vous ?",
    quote: "Citation",
    highlights: "Faits Saillants",
    perspectives: "Perspectives",
    quickQuestions: "Questions Rapides",
    technicalDetails: "Détails Techniques",
    industryImpact: "Impact sur l'Industrie",
    timeline: "Chronologie",
    travelAdvisory: "Avis aux Voyageurs",
    internationalReactions: "Réactions Internationales",
    actionItems: "Actions à Mener",
    scientificSignificance: "Importance Scientifique",
    performanceStatistics: "Statistiques de Performance",
    sources: "Sources",
  },
  category: {
    africa: "Afrique",
    ai: "IA",
    apple: "Apple",
    argentina: "Argentine",
    australia: "Australie",
    austria: "Autriche",
    bay: "Baie",
    belgium: "Belgique",
    bitcoin: "Bitcoin",
    brazil: "Brésil",
    business: "Affaires",
    canada: "Canada",
    catholic: "Catholique",
    china: "Chine",
    coffee: "Café",
    colombia: "Colombie",
    costa_rica: "Costa Rica",
    croatia: "Croatie",
    cryptocurrency: "Cryptomonnaies",
    cybersecurity: "Cybersécurité",
    czech_republic: "République Tchèque",
    denmark: "Danemark",
    economy: "Économie",
    estonia: "Estonie",
    europe: "Europe",
    finland: "Finlande",
    formula_1: "Formule 1",
    france: "France",
    french_music: "Musique Française",
    gaming: "Jeux Vidéo",
    germany_hesse: "Allemagne | Hesse",
    germany: "Allemagne",
    google: "Google",
    greece: "Grèce",
    healthcare_usa: "Santé aux États-Unis",
    hong_kong: "Hong Kong",
    hungary: "Hongrie",
    india_tamil_nadu: "Inde | Tamil Nadu",
    india: "Inde",
    iracing: "iRacing et Sim Racing",
    iran: "Iran",
    ireland: "Irlande",
    israel: "Israël",
    italy: "Italie",
    japan: "Japon",
    linux_oss: "Linux et Open Source",
    lithuania: "Lituanie",
    mexico: "Mexique",
    microsoft: "Microsoft",
    new_zealand: "Nouvelle-Zélande",
    nfl: "NFL",
    nhl: "LNH",
    nintendo: "Nintendo",
    norway: "Norvège",
    pakistan: "Pakistan",
    palestine: "Palestine",
    philippines: "Philippines",
    podcasting: "Podcasting",
    poland: "Pologne",
    portugal: "Portugal",
    privacy: "Confidentialité",
    romania: "Roumanie",
    russia: "Russie",
    science: "Science",
    serbia: "Serbie",
    simulation_games: "Jeux de Simulation",
    singapore: "Singapour",
    slovakia: "Slovaquie",
    slovenia: "Slovénie",
    south_korea: "Corée du Sud",
    spain: "Espagne",
    sports: "Sports",
    sweden: "Suède",
    switzerland_de: "Suisse (DE)",
    switzerland_fr: "Suisse (FR)",
    taiwan: "Taïwan",
    technology: "Technologie",
    thailand: "Thaïlande",
    the_netherlands: "Pays-Bas",
    three_d_printing: "Impression 3D",
    turkey: "Turquie",
    uk: "Royaume-Uni",
    ukraine: "Ukraine",
    usa_austin: "États-Unis | Austin, TX",
    usa_chicago: "États-Unis | Chicago",
    usa_colorado: "États-Unis | Colorado",
    usa_hawaii: "États-Unis | Hawaï",
    usa_michigan: "États-Unis | Michigan",
    usa_minnesota: "États-Unis | Minnesota",
    usa_nevada: "États-Unis | Nevada",
    usa_nyc: "États-Unis | New York",
    usa_ohio: "États-Unis | Ohio",
    usa_utah: "États-Unis | Utah",
    usa_vermont: "États-Unis | Vermont",
    usa_virginia: "États-Unis | Virginie",
    usa_washington: "États-Unis | Washington",
    usa: "États-Unis",
    watches_and_horology: "Montres et Horlogerie",
    world: "Monde",
  },
} as const;
