import { InterfaceStrings } from "../type";

export const strings: InterfaceStrings = {
  general: {
    loading: "Caricamento...",
  },
  title: {
    feeds: "Feed",
    news: "Notizie",
    category: "Categorie",
    stories: "Storie",
    availableDetails: "Dettagli disponibili",
  },
  section: {
    historicalBackground: "Contesto Storico",
    humanitarianImpact: "Impatto Umanitario",
    didYouKnow: "Lo Sapevi?",
    quote: "Citazione",
    highlights: "Punti Salienti",
    perspectives: "Prospettive",
    quickQuestions: "Domande Rapide",
    technicalDetails: "Dettagli Tecnici",
    industryImpact: "Impatto sul Settore",
    timeline: "Cronologia",
    travelAdvisory: "Avviso di Viaggio",
    internationalReactions: "Reazioni Internazionali",
    actionItems: "Punti d'Azione",
    scientificSignificance: "Importanza Scientifica",
    performanceStatistics: "Statistiche delle Prestazioni",
    sources: "Fonti",
  },
  category: {
    africa: "Africa",
    ai: "IA",
    apple: "Apple",
    argentina: "Argentina",
    australia: "Australia",
    austria: "Austria",
    bay: "Baia",
    belgium: "Belgio",
    bitcoin: "Bitcoin",
    brazil: "Brasile",
    business: "Economia",
    canada: "Canada",
    catholic: "Cattolico",
    china: "Cina",
    coffee: "Caffè",
    colombia: "Colombia",
    costa_rica: "Costa Rica",
    croatia: "Croazia",
    cryptocurrency: "Criptovalute",
    cybersecurity: "Sicurezza Informatica",
    czech_republic: "Repubblica Ceca",
    denmark: "Danimarca",
    economy: "Economia",
    estonia: "Estonia",
    europe: "Europa",
    finland: "Finlandia",
    formula_1: "Formula 1",
    france: "Francia",
    french_music: "Musica Francese",
    gaming: "Videogiochi",
    germany_hesse: "Germania | Assia",
    germany: "Germania",
    google: "Google",
    greece: "Grecia",
    healthcare_usa: "Sanità USA",
    hong_kong: "Hong Kong",
    hungary: "Ungheria",
    india_tamil_nadu: "India | Tamil Nadu",
    india: "India",
    iracing: "iRacing e Sim Racing",
    iran: "Iran",
    ireland: "Irlanda",
    israel: "Israele",
    italy: "Italia",
    japan: "Giappone",
    linux_oss: "Linux e Open Source",
    lithuania: "Lituania",
    mexico: "Messico",
    microsoft: "Microsoft",
    new_zealand: "Nuova Zelanda",
    nfl: "NFL",
    nhl: "NHL",
    nintendo: "Nintendo",
    norway: "Norvegia",
    pakistan: "Pakistan",
    palestine: "Palestina",
    philippines: "Filippine",
    podcasting: "Podcasting",
    poland: "Polonia",
    portugal: "Portogallo",
    privacy: "Privacy",
    romania: "Romania",
    russia: "Russia",
    science: "Scienza",
    serbia: "Serbia",
    simulation_games: "Giochi di Simulazione",
    singapore: "Singapore",
    slovakia: "Slovacchia",
    slovenia: "Slovenia",
    south_korea: "Corea del Sud",
    spain: "Spagna",
    sports: "Sport",
    sweden: "Svezia",
    switzerland_de: "Svizzera (DE)",
    switzerland_fr: "Svizzera (FR)",
    taiwan: "Taiwan",
    technology: "Tecnologia",
    thailand: "Thailandia",
    the_netherlands: "Paesi Bassi",
    three_d_printing: "Stampa 3D",
    turkey: "Turchia",
    uk: "Regno Unito",
    ukraine: "Ucraina",
    usa_austin: "USA | Austin, TX",
    usa_chicago: "USA | Chicago",
    usa_colorado: "USA | Colorado",
    usa_hawaii: "Stati Uniti | Hawaii",
    usa_michigan: "USA | Michigan",
    usa_minnesota: "USA | Minnesota",
    usa_nevada: "Stati Uniti | Nevada",
    usa_nyc: "USA | New York City",
    usa_ohio: "USA | Ohio",
    usa_utah: "USA | Utah",
    usa_vermont: "Stati Uniti | Vermont",
    usa_virginia: "USA | Virginia",
    usa_washington: "Stati Uniti | Washington",
    usa: "USA",
    watches_and_horology: "Orologi e Orologeria",
    world: "Mondo",
  },
  feature: {
    small_web_feed: "Piccolo Web",
  },
} as const;
