import { InterfaceStrings } from "../type";

export const strings: InterfaceStrings = {
  general: {
    loading: "読み込み中...",
  },
  title: {
    feeds: "フィード",
    news: "ニュース",
    category: "カテゴリー",
    stories: "ニュース",
    availableDetails: "利用可能な詳細",
  },
  section: {
    historicalBackground: "歴史的背景",
    humanitarianImpact: "人道的影響",
    didYouKnow: "知っていましたか？",
    quote: "引用",
    highlights: "ハイライト",
    perspectives: "視点",
    quickQuestions: "簡単な質問",
    technicalDetails: "技術的な詳細",
    industryImpact: "業界への影響",
    timeline: "出来事のタイムライン",
    travelAdvisory: "旅行アドバイザリー",
    internationalReactions: "国際的反応",
    actionItems: "アクション項目",
    scientificSignificance: "科学的意義",
    performanceStatistics: "パフォーマンス統計",
    sources: "出典",
  },
  category: {
    africa: "アフリカ",
    ai: "AI（人工知能）",
    apple: "アップルワールド",
    argentina: "アルゼンチン",
    australia: "オーストラリア",
    austria: "オーストリア",
    bay: "アメリカ ベイエリア",
    belgium: "ベルギー",
    bitcoin: "Bitcoin",
    brazil: "ブラジル",
    business: "ビジネス",
    canada: "カナダ",
    catholic: "カトリック",
    china: "中国",
    coffee: "コーヒー",
    colombia: "コロンビア",
    costa_rica: "コスタリカ",
    croatia: "クロアチア",
    cryptocurrency: "暗号通貨",
    cybersecurity: "サイバーセキュリティ",
    czech_republic: "チェコ",
    denmark: "デンマーク",
    economy: "経済",
    estonia: "エストニア",
    europe: "ヨーロッパ",
    finland: "フィンランド",
    formula_1: "フォーミュラ1",
    france: "フランス",
    french_music: "フランス音楽",
    gaming: "ゲーム",
    germany_hesse: "ドイツ | ヘッセン州",
    germany: "ドイツ",
    google: "Google",
    greece: "ギリシャ",
    healthcare_usa: "ヘルスケア | USA",
    hong_kong: "香港",
    hungary: "ハンガリー",
    india_tamil_nadu: "インド | タミル・ナードゥ州",
    india: "インド",
    iracing: "iRacing と sim レーシング",
    iran: "イラン",
    ireland: "アイルランド",
    israel: "イスラエル",
    italy: "イタリア",
    japan: "日本",
    linux_oss: "Linux & OSS",
    lithuania: "リトアニア",
    mexico: "メキシコ",
    microsoft: "Microsoft",
    new_zealand: "ニュージーランド",
    nfl: "NFL",
    nhl: "NHL",
    nintendo: "Nintendo",
    norway: "ノルウェー",
    pakistan: "パキスタン",
    palestine: "パレスチナ",
    philippines: "フィリピン",
    podcasting: "ポッドキャスティング",
    poland: "ポーランド",
    portugal: "ポルトガル",
    privacy: "プライバシー",
    romania: "ルーマニア",
    russia: "ロシア",
    science: "科学",
    serbia: "セルビア",
    simulation_games: "シミュレーションゲーム",
    singapore: "シンガポール",
    slovakia: "スロバキア",
    slovenia: "スロベニア",
    south_korea: "韓国",
    spain: "スペイン",
    sports: "スポーツ",
    sweden: "スウェーデン",
    switzerland_de: "スイス（ドイツ語圏）",
    switzerland_fr: "スイス（フランス語圏）",
    taiwan: "台湾",
    technology: "テクノロジー",
    thailand: "タイ",
    the_netherlands: "オランダ",
    three_d_printing: "3D プリンティング",
    turkey: "トルコ",
    uk: "イギリス",
    ukraine: "ウクライナ",
    usa_austin: "アメリカ | オースティン、TX",
    usa_chicago: "アメリカ | シカゴ",
    usa_colorado: "アメリカ | コロラド州",
    usa_hawaii: "アメリカ | ハワイ",
    usa_michigan: "アメリカ | ミシガン州",
    usa_minnesota: "アメリカ | ミネソタ州",
    usa_nevada: "アメリカ | ネバダ州",
    usa_nyc: "アメリカ | ニューヨーク",
    usa_ohio: "アメリカ | オハイオ州",
    usa_utah: "アメリカ | ユタ州",
    usa_vermont: "アメリカ | バーモント州",
    usa_virginia: "アメリカ | バージニア州",
    usa_washington: "アメリカ | ワシントン州",
    usa: "アメリカ",
    watches_and_horology: "時計と時計製造",
    world: "世界",
  },
  feature: {
    small_web_feed: "小規模ウェブ",
  },
} as const;
