import { InterfaceStrings } from "../type";

export const strings: InterfaceStrings = {
  general: {
    loading: "Carregando...",
  },
  title: {
    feeds: "Feeds",
    news: "Notícias",
    category: "Categorias",
    stories: "Histórias",
    availableDetails: "Detalhes disponíveis",
  },
  section: {
    historicalBackground: "Contexto Histórico",
    humanitarianImpact: "Impacto Humanitário",
    didYouKnow: "Você Sabia?",
    quote: "Citação",
    highlights: "Destaques",
    perspectives: "Perspectivas",
    quickQuestions: "Perguntas Rápidas",
    technicalDetails: "Detalhes Técnicos",
    industryImpact: "Impacto na Indústria",
    timeline: "Linha do Tempo",
    travelAdvisory: "Aviso de Viagem",
    internationalReactions: "Reações Internacionais",
    actionItems: "Itens de Ação",
    scientificSignificance: "Significância Científica",
    performanceStatistics: "Estatísticas de Desempenho",
    sources: "Fontes",
  },
  category: {
    africa: "África",
    ai: "IA",
    apple: "Apple",
    argentina: "Argentina",
    australia: "Austrália",
    austria: "Áustria",
    bay: "Baía",
    belgium: "Bélgica",
    bitcoin: "Bitcoin",
    brazil: "Brasil",
    business: "Negócios",
    canada: "Canadá",
    catholic: "Católico",
    china: "China",
    coffee: "Café",
    colombia: "Colômbia",
    costa_rica: "Costa Rica",
    croatia: "Croácia",
    cryptocurrency: "Criptomoedas",
    cybersecurity: "Cibersegurança",
    czech_republic: "República Checa",
    denmark: "Dinamarca",
    economy: "Economia",
    estonia: "Estônia",
    europe: "Europa",
    finland: "Finlândia",
    formula_1: "Fórmula 1",
    france: "França",
    french_music: "Música Francesa",
    gaming: "Jogos",
    germany_hesse: "Alemanha | Hesse",
    germany: "Alemanha",
    google: "Google",
    greece: "Grécia",
    healthcare_usa: "Saúde nos EUA",
    hong_kong: "Hong Kong",
    hungary: "Hungria",
    india_tamil_nadu: "Índia | Tamil Nadu",
    india: "Índia",
    iracing: "iRacing e Sim Racing",
    iran: "Irã",
    ireland: "Irlanda",
    israel: "Israel",
    italy: "Itália",
    japan: "Japão",
    linux_oss: "Linux e Código Aberto",
    lithuania: "Lituânia",
    mexico: "México",
    microsoft: "Microsoft",
    new_zealand: "Nova Zelândia",
    nfl: "NFL",
    nhl: "NHL",
    nintendo: "Nintendo",
    norway: "Noruega",
    pakistan: "Paquistão",
    palestine: "Palestina",
    philippines: "Filipinas",
    podcasting: "Podcasting",
    poland: "Polônia",
    portugal: "Portugal",
    privacy: "Privacidade",
    romania: "Romênia",
    russia: "Rússia",
    science: "Ciência",
    serbia: "Sérvia",
    simulation_games: "Jogos de Simulação",
    singapore: "Singapura",
    slovakia: "Eslováquia",
    slovenia: "Eslovênia",
    south_korea: "Coreia do Sul",
    spain: "Espanha",
    sports: "Esportes",
    sweden: "Suécia",
    switzerland_de: "Suíça (DE)",
    switzerland_fr: "Suíça (FR)",
    taiwan: "Taiwan",
    technology: "Tecnologia",
    thailand: "Tailândia",
    the_netherlands: "Países Baixos",
    three_d_printing: "Impressão 3D",
    turkey: "Turquia",
    uk: "Reino Unido",
    ukraine: "Ucrânia",
    usa_austin: "EUA | Austin, TX",
    usa_chicago: "EUA | Chicago",
    usa_colorado: "EUA | Colorado",
    usa_hawaii: "EUA | Havaí",
    usa_michigan: "EUA | Michigan",
    usa_minnesota: "EUA | Minnesota",
    usa_nevada: "EUA | Nevada",
    usa_nyc: "EUA | New York",
    usa_ohio: "EUA | Ohio",
    usa_utah: "EUA | Utah",
    usa_vermont: "EUA | Vermont",
    usa_virginia: "EUA | Virgínia",
    usa_washington: "EUA | Washington",
    usa: "EUA",
    watches_and_horology: "Relógios e Relojoaria",
    world: "Mundo",
  },
  feature: {
    small_web_feed: "Pequena Web",
  },
} as const;
