import { InterfaceStrings } from "../type";

export const strings: InterfaceStrings = {
  general: {
    loading: "Загрузка...",
  },
  title: {
    category: "Категории",
    stories: "Новости",
    availableDetails: "Доступные детали",
  },
  section: {
    historicalBackground: "Историческая справка",
    humanitarianImpact: "Гуманитарное воздействие",
    didYouKnow: "Знаете ли вы?",
    quote: "Цитаты",
    highlights: "Основные моменты",
    perspectives: "Перспективы",
    quickQuestions: "Быстрые вопросы",
    technicalDetails: "Технические детали",
    industryImpact: "Воздействие на отрасль",
    timeline: "Хроника событий",
    travelAdvisory: "Советы для путешествующих",
    internationalReactions: "Международная реакция",
    actionItems: "Пункты действий",
    scientificSignificance: "Научное значение",
    performanceStatistics: "Статистика эффективности",
    sources: "Источники",
  },
  category: {
    africa: "Африка",
    ai: "ИИ",
    apple: "Apple",
    argentina: "Аргентина",
    australia: "Австралия",
    austria: "Австрия",
    bay: "США | SF",
    belgium: "Бельгия",
    bitcoin: "Bitcoin",
    brazil: "Бразилия",
    business: "Бизнес",
    canada: "Канада",
    catholic: "Католический",
    china: "Китай",
    coffee: "Кофе",
    colombia: "Колумбия",
    costa_rica: "Коста-Рика",
    croatia: "Хорватия",
    cryptocurrency: "Криптовалюта",
    cybersecurity: "Кибербезопасность",
    czech_republic: "Чехия",
    denmark: "Дания",
    economy: "Экономика",
    estonia: "Эстония",
    europe: "Европа",
    finland: "Финляндия",
    formula_1: "Формула 1",
    france: "Франция",
    french_music: "Французская музыка",
    gaming: "Игры",
    germany_hesse: "Германия | Гессен",
    germany: "Германия",
    google: "Google",
    greece: "Греция",
    healthcare_usa: "Здравоохранение | США",
    hong_kong: "Гонконг",
    hungary: "Венгрия",
    india_tamil_nadu: "Индия | Тамил Наду",
    india: "Индия",
    iracing: "iRacing и симуляторы гонок",
    iran: "Иран",
    ireland: "Ирландия",
    israel: "Израиль",
    italy: "Италия",
    japan: "Япония",
    linux_oss: "Linux & OSS",
    lithuania: "Литва",
    mexico: "Мексика",
    microsoft: "Microsoft",
    new_zealand: "Новая Зеландия",
    nfl: "NFL",
    nhl: "NHL",
    nintendo: "Nintendo",
    norway: "Норвегия",
    pakistan: "Пакистан",
    palestine: "Палестина",
    philippines: "Филиппины",
    podcasting: "Подкастинг",
    poland: "Польша",
    portugal: "Португалия",
    privacy: "Приватность",
    romania: "Румыния",
    russia: "Россия",
    science: "Наука",
    serbia: "Сербия",
    simulation_games: "Игры-симуляторы",
    singapore: "Сингапур",
    slovakia: "Словакия",
    slovenia: "Словения",
    south_korea: "Южная Корея",
    spain: "Испания",
    sports: "Спорт",
    sweden: "Швеция",
    switzerland_de: "Швейцария (DE)",
    switzerland_fr: "Швейцария (FR)",
    taiwan: "Тайвань",
    technology: "Технологии",
    thailand: "Таиланд",
    the_netherlands: "Нидерланды",
    three_d_printing: "3D-печать",
    turkey: "Турция",
    uk: "Великобритания",
    ukraine: "Украина",
    usa_austin: "США | Остин, TX",
    usa_chicago: "США | Чикаго",
    usa_colorado: "США | Колорадо",
    usa_hawaii: "США | Гаваи",
    usa_michigan: "США | Мичиган",
    usa_minnesota: "США | Миннесота",
    usa_nevada: "США | Невада",
    usa_nyc: "США | Нью-Йорк",
    usa_ohio: "США | Огайо",
    usa_utah: "США | Юта",
    usa_vermont: "США | Вермонт",
    usa_virginia: "США | Вирджиния",
    usa_washington: "США | Вашингтон",
    usa: "США",
    watches_and_horology: "Часы и часовое дело",
    world: "Мир",
  },
} as const;
